### Registro de usuario (POST)
POST http://127.0.0.1:5000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123"
}

### Autenticación (login) - obtener el token
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

{% client.global.set("token", response.json().token); %}

### USUARIOS

### Obtener todos los usuarios (GET)
GET http://127.0.0.1:5000/api/users
Authorization: Bearer {{token}}

### Obtener un usuario específico (GET)
GET http://127.0.0.1:5000/api/users/1
Authorization: Bearer {{token}}

### Crear un nuevo usuario (POST)
POST http://127.0.0.1:5000/api/users
Content-Type: application/json

{
  "name": "Nuevo Usuario",
  "email": "nuevo@example.com",
  "password": "password123"
}

### Actualizar un usuario existente (PUT)
PUT http://127.0.0.1:5000/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Usuario Actualizado",
  "email": "actualizado@example.com",
  "password": "password123"
}

### Eliminar un usuario (DELETE)
DELETE http://127.0.0.1:5000/api/users/1
Authorization: Bearer {{token}}
